### ISSUE TITLE
Problème de téléchargement de la dernière release

### ISSUE THREAD

**Issue by 3079rod** [opt-nc/opt-logging#145]
Bonjour,
quand j'essaye de télécharger la dernière version d'OPT-LOGGING, j'ai une erreur:
![image](https://user-images.githubusercontent.com/66574576/198419821-71b36080-f71a-46f0-80d5-1f7754736d2e.png)
 que ce soit la version 3.0.0 ou 3.0.1

Dans l'attente de votre retour.

Bonne journée

**Comment by adriens** [comment]
j'ai lancé les prebuilds

![image](https://user-images.githubusercontent.com/5235127/198466352-3f5e54e4-f569-4aa7-b102-90298dc9a77e.png)


👉  @3079rod c'est pas mieux maintenant ?

**Comment by 3079rod** [comment]
Yo, je viens de le teste, c'est bon çà passe.  Merci

**Comment by adriens** [comment]
Bobn ben c'était bien ça... fallait juste prebuidler la dep sur jitpack.

Merci pour le fednack @3079rod :+1:
