### ISSUE TITLE
`json` de démo du README non valide

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-logging#47]
Actuellement, le `json` donné en exemple n'est pas valide 😄 : 

```
Error: Parse error on line 4:
...n": 1,	"pays": {		\		"id\":1,\"libell
---------------------^
Expecting 'STRING', '}', got 'undefined'
```

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/149723526-78ceceb5-7e8e-4c40-94c1-3b1382f7a81b.png)

lmpeccable. Bon retour de congés  @mbarre

**Comment by mbarre** [comment]
Merci @adriens .
Mais que fais tu par ici toi ? Tes congés ne sont pas terminés ! :no_entry_sign:
