### ISSUE TITLE
Upgrade to SB v2.6.4

### ISSUE THREAD

**Issue by adriens** [opt-nc/opt-logging#78]
-  ~Upgrader SB : cf [v2.6.4](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4)~
- [x] Merger #76 
- [x] Merger #77 
- [x] Dropper une release
- [x] Faire une comm' sur comment s'abonner aux news de opt-logging (@adriens ), et communqiuer sur arrivée prochaine de la [2.7.0](https://twitter.com/springboot/status/1496965865815765010)

**Comment by Dougniel** [comment]
> * [ ]  Faire une comm' sur comment s'abonner aux news de opt-logging (@adriens ), et communqiuer sur arrivée prochaine de la [2.7.0](https://twitter.com/springboot/status/1496965865815765010)

@adriens, On n'avait pas dit que opt-logging était dépréciée ?

**Comment by adriens** [comment]
Les devs onPrem l'utllisent toujurs puisque sur le socle

**Comment by adriens** [comment]
l'idée est donc de leur fournir une vesion maintenue et d'aculturer les gens à suivre/monitorer les montées de versions de leurs dépendances... **même sans dependabot**

**Comment by Dougniel** [comment]
> Les devs onPrem l'utllisent toujurs puisque sur le socle

D'accord, mais de là à faire de la comm dessus, je trouve que cela va dans la promotion de ce composant et ça nous donne une comm  incohérente



> l'idée est donc de leur fournir une vesion maintenue et d'aculturer les gens à suivre/monitorer les montées de versions de leurs dépendances... **même sans dependabot**

Je comprends, mais je pense qu'il faut trouver un autre sujet

**Comment by adriens** [comment]
C'est pas incohérent, cette lib est utilisée en masse à l'OPT. Et on maintient ce que l'on utilise. Il n'y pas que nous...et c'est pas demain que tous les devs seront sur GH comme nous en avons la chance **> Ne pas oublier ça.**

D'autres sujets viendront compléter. **Mais pour l'instant, ce sujet sera poussé.** Un investissement a été effectué, pour montrer la continuité. C'est didactique.

**Comment by adriens** [comment]
J'attends les upgrades et release donc stp.

**Comment by Dougniel** [comment]
> * [ ]  Upgrader SB : cf [v2.6.4](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4)

@adriens, il n'y a pas de spring-boot car il s'agit d'une lib, par contre il y a une dépendance spring-context qui a été upgradé à la dernière version ce qui signifie que ça ne devrait pas poser pb avec les projets qui vont utiliser cette dépendance

**Comment by Dougniel** [comment]
Bon galère 😅  semantic-release : 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/39691264/155699197-490f053f-6357-4fb7-b5f1-b2ff060c8fdb.png">
Alors que :
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/39691264/155699357-d41e8af3-4799-4603-ae92-d9d8f38ec8bb.png">
et : 
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/39691264/155699458-e6a48370-ea47-488b-ad32-0b9378b47529.png">

**Comment by Dougniel** [comment]
La raison au fait que la release GitHub n'est pas été générée est ici : https://github.com/opt-nc/opt-logging/commit/a227cdff578fcc055a40a9be5ac72feba6be615b

J'ai fait une issue la dessus à @mbarre car je ne sais pas si c'était volontaire ou non ou quels ont été les pb que @mbarre a rencontré : https://github.com/opt-nc/opt-logging/issues/81

En attendant, j'ai généré la release manuellement

**Comment by adriens** [comment]
> Bon galère 😅 semantic-release

Oui, on dirrait bien cf https://github.com/opt-nc/conventional-commit/pull/34

**Comment by adriens** [comment]
> En attendant, j'ai généré la release manuellement

👍

**Comment by adriens** [comment]
Comm' faite 👍
