### ISSUE TITLE
opt-logging : semantic-release ne génère plus de release GitHub

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-logging#81]
@mbarre, 

Au sujet de ce [problème](https://github.com/opt-nc/opt-logging/issues/78#issuecomment-1050730654) qui semble causé par ce commit https://github.com/opt-nc/opt-logging/commit/a227cdff578fcc055a40a9be5ac72feba6be615b

Est-ce volontaire d'avoir supprimé le plugin GitHub ?

**Comment by adriens** [comment]
🤔

**Comment by adriens** [comment]
idem souci sur https://github.com/opt-nc/conventional-commit/issues/23

**Comment by adriens** [comment]
<3
