### ISSUE TITLE
🛡️ Configurer le Code Scanning 🛡️ 

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-logging#96]
https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

**Comment by adriens** [comment]
Déja fait cf https://github.com/opt-nc/opt-logging/blob/main/.github/workflows/codeql-analysis.yml

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/160723919-957f505e-177e-4fa3-a55c-2c3450362f2c.png)
